"""added user token to car table

Revision ID: 10990854b930
Revises: 8ae3de27bd83
Create Date: 2021-11-10 22:19:52.788012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10990854b930'
down_revision = '8ae3de27bd83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('user_token', sa.String(), nullable=False))
    op.create_foreign_key(None, 'car', 'user', ['user_token'], ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car', type_='foreignkey')
    op.drop_column('car', 'user_token')
    # ### end Alembic commands ###
