"""created car table

Revision ID: 8ae3de27bd83
Revises: 4cab5700217e
Create Date: 2021-11-10 20:13:18.929319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae3de27bd83'
down_revision = '4cab5700217e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('make', sa.String(length=150), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('year', sa.String(length=150), nullable=False),
    sa.Column('topSpeed', sa.String(length=150), nullable=True),
    sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
